### ISSUE TITLE
Sphinx Warning

### ISSUE THREAD

**Issue by hagankristen** [hagankristen/LaserEye_testing#3]
See open pull request. 
Sphinx warning. 
@mlp6
@suyashkumar

**Comment by mlp6** [comment]
Two issues that I see on quick inspection:

1. `index.rst` doesn't have the list of rst files that `autodoc` generated that you want `sphinx` to actually include in the documentation.
2. You don't need to build documentation for the `test*.py` files, so you can exclude the `test*.rst` from your `index.rst` file.

That doesn't address the numpy issue, but that issue appears to be related to the test docs, so that problem should "disappear".

**Comment by hagankristen** [comment]
@mlp6  
i forgot to commit the index.rst file. i do have the rst files generated in index.rst, so thats not the issue. 
this message comes up whether or not i have the test file in index .rst
